### ISSUE TITLE
Get lat, lon for Station

### ISSUE THREAD

**Issue by NZTideMan** [raspishake/rscu#1]
rscu is an excellent facility.  This a suggestion for an enhancement.

Typing in the lat, lon for each Station each time you run the program is a bit laborious.
This info is available, for example, at [http://ds.iris.edu/mda/AM/RC144/]()
It is also be available in more compact form at:
[https://fdsnws.raspberryshakedata.com/fdsnws/station/1/query?net=AM&sta=RC144&level=channel&format=text&nodata=404]()
It would be nice if the lat lon popped up when you typed the Station.

Alternatively, the details of the station (location and component) that you enter manually could be remembered, so that you don't have to type them in each time.

**Comment by NZTideMan** [comment]
I'm just learning Python, so please excuse my amateurish programming, but here is a routine that will recover the stations coordinates:
```python
from obspy import read_inventory
def RSgetloc(station,
				net="AM"):

	base_url='https://fdsnws.raspberryshakedata.com/'
	url=base_url + '/fdsnws/station/1/query?network=' + net + '&station=' + station + '&level=resp&format=xml'
	inv = read_inventory(url)
	net=inv[0]
	for station in net:
		lon=station.longitude
		lat=station.latitude
	return lat,lon			
lat,lon=RSgetloc('R00B9')
print(lat,lon)
```

**Comment by iannesbitt** [comment]
This is in the list of future enhancements. Thanks @NZTideMan
